FROM jenkins/jenkins:lts

USER root

RUN apt-get update \
    && apt-get install -y docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd -for -g 999 docker \
    && usermod -aG docker jenkins

USER jenkins